modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "mtr_beijing_addon"
version = "${version}"
displayName = "MTR Beijing Addon"
entrypoint = "com.fangsu.beijing.BeijingAddon"